### ISSUE TITLE
Evaluation performance

### ISSUE THREAD

**Issue by FangGet** [Gorilla-Lab-SCUT/VISTA#2]
hello, @AndlollipopDE, your work is great, I trained the model with all configurations unchanged but got a strange evaluation performance. the mAVE/mAAE/NDS is faraway behind your pretrained model.

| name |    mAP  | mATE     |   mASE   | mAOE   | mAVE   | mAAE   | NDS   |
| ----| ---- | ---- | ---- |---- |---- |---- |---- |
|   Yours   |   0.6283   |   0.2925   |   0.2452   |  0.2573    |    0.1980  |   0.1967   |  0.6952   |
|   Own   |   0.6298   |   0.2890   |   0.2457   |   0.2563   |   1.3230   |   0.4685   |  0.5890   |

mAP seems normal for all classes, but the NDS is really strange, can you give some suggestion for this?

**Comment by FangGet** [comment]
I commented the aforementioned line https://github.com/Gorilla-Lab-SCUT/VISTA/blob/2498d4956648430ed4083e301e562e4b99acd363/det3d/datasets/utils/create_gt_database.py#L119
and retrained the model, everything seems fine now,

| name |    mAP  | mATE     |   mASE   | mAOE   | mAVE   | mAAE   | NDS   |
| ----| ---- | ---- | ---- |---- |---- |---- |---- |
|   Yours   |   0.6283   |   0.2925   |   0.2452   |  0.2573    |    0.1980  |   0.1967   |  0.6952   |
|   Own   |   0.6301   |   0.2937   |   0.2456   |   0.2563   |   0.2014   |   0.1936   |  0.6872  |

**Comment by StiphyJay** [comment]
> I commented the aforementioned line

how did you reproduce this results. First regenerate the dataset info and train their model without modification on config file? Looks like their dataset length only 7724, is right?
